name: Security Flow Action

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Use v2 for stability
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Snyk
        run: pip install snyk
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --sarif-file-output=snyk.sarif --directory=/github/workspace/app
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
  build:
    needs: security
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: example_django_app
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
