name: Security Flow Action

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write
  issues: write

jobs:
  security:
    runs-on: ubuntu-latest
    outputs:
      findings: ${{ steps.check_findings.outputs.findings }}
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities (Python)
        run: |
          docker run --name snykpython --workdir /github/workspace \
            -e "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" \
            -e "GITHUB_ACTIONS=true" \
            -e "CI=true" \
            -v "/home/runner/work/security_action/security_action/app:/github/workspace" \
            snyk/snyk:python  snyk test --sarif-file-output=snyk-python.sarif || true

      - name: Get snyk.sarif
        run: |
          docker cp snykpython:/github/workspace/snyk-python.sarif ./app/snyk-python.sarif

      - name: Add scan results to Jira
        run: |
          echo "Add scan results to Jira"
          pip install jira
          python ./helpers/sarif_parser.py --jira_url "${{ secrets.JIRA_URL }}" --jira_username "${{ secrets.JIRA_USERNAME }}" --jira_token "${{ secrets.JIRA_TOKEN }}" --project_key "${{ secrets.JIRA_PROJECT }}" --sarif_file "./app/snyk-python.sarif"
      
      - name: Upload python result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./app/snyk-python.sarif
          category: python

      - name: Check SARIF for findings
        id: check_findings
        run: |
          findings_count=$(jq '[.runs[].results | length] | add' ./app/snyk-python.sarif)
          if [[ "$findings_count" -gt 0 ]]; then
            echo "findings=true" >> $GITHUB_ENV
            echo "::set-output name=findings::true"
          else
            echo "findings=false" >> $GITHUB_ENV
            echo "::set-output name=findings::false"
          fi

  build_and_scan:
    needs: security
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: example_django_app
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag the image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        with:
          image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          args: --file=Dockerfile --severity-threshold=high

      - name: Add scan results to Jira
        run: |
          echo "Add scan results to Jira"
          pip install jira
          python ./helpers/sarif_parser.py --jira_url "${{ secrets.JIRA_URL }}" --jira_username "${{ secrets.JIRA_USERNAME }}" --jira_token "${{ secrets.JIRA_TOKEN }}" --project_key "${{ secrets.JIRA_PROJECT }}" --sarif_file "snyk.sarif"
      
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
          category: docker
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          aws s3 cp snyk.sarif s3://cn-security-action/sarif/snyk.sarif
  # require_approval:
  #   if: ${{ env.findings }} == 'true'
  #   needs: [security, build_and_scan]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: approval-required
  #     url: ${{ steps.deploy.outputs.deployment-url }}
  #   steps:
  #     - name: Wait for Approval
  #       run: echo "This job requires manual approval because findings were detected."
  review_and_approve:
    if: needs.security.outputs.findings == 'true'
    needs: [security, build_and_scan]
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: mhw29
          minimum-approvals: 1
          issue-title: "Security findings detected. Please review and approve."
          issue-body: "Please approve or deny the build to continue deployment."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
  deploy:
    needs: [build_and_scan, review_and_approve]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
