name: Security Flow Action

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities (Python)
        run: |
          docker run --name snykpython --workdir /github/workspace \
            -e "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" \
            -e "GITHUB_ACTIONS=true" \
            -e "CI=true" \
            -v "/home/runner/work/security_action/security_action/app:/github/workspace" \
            snyk/snyk:python  snyk test --sarif-file-output=snyk-python.sarif || true

      - name: Get snyk.sarif
        run: |
          docker cp snykpython:/github/workspace/snyk-python.sarif ./app/snyk-python.sarif

      - name: Upload python result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./app/snyk-python.sarif
          category: Python

      - name: Scan the Docker image with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          docker run --rm \
            -e "SNYK_TOKEN=${SNYK_TOKEN}" \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            -v "$(pwd):/project" \
            snyk/snyk:docker snyk test --docker ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --file=Dockerfile  --sarif-file-output=snyk-docker.sarif || true
        
        - name: Get snyk-docker.sarif
          run: |
            docker cp snykdocker:/github/workspace/snyk-docker.sarif ./app/snyk-docker.sarif

        - name: Upload docker result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: ./app/snyk-docker.sarif
            category: Docker
  build:
    needs: security
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: example_django_app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag the image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
