name: Security Flow Action

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      working-directory: ./app/example_django_app
    steps:
      - uses: actions/checkout@master
      - name: Print current directory
        run: pwd
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --workdir=${{ env.working-directory }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
  
  build:
    needs: security
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: example_django_app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
